version: "3"

networks:
  laravel-docker:

services:
  nginx:
    image: nginx
    container_name: shapeyou_nginx
    restart: always
    ports:
      - "8484:80"
    volumes:
      - ./:/var/www/html
      - ./development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-docker

  php:
    build:
      context: .
      dockerfile: development/Dockerfile
    container_name: shapeyou_php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-docker