version: "3"

networks:
  UB:

services:
  nginx:
    image: nginx:stable
    container_name: UB_nginx
    restart: always
    volumes:
      - ./:/var/www/html
      - ./development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - UB

  mysql:
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: pMJ5><P6\5KVaHR@
      MYSQL_DATABASE: ub_db
    restart: always
    networks:
      - UB

  phpmyadmin:
    image: phpmyadmin:5.1.3
    environment: 
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://ub.checkmy.dev/phpmyadmin
  php:
    build:
      context: .
      dockerfile: development/Dockerfile
    container_name: UB_php
    volumes:
      - ./:/var/www/html
    networks:
      - UB